apiVersion: v1
kind: Service
metadata:
 name: nodeport-svc
 namespace: ms
spec:
 type: NodePort
 selector:
   app: my-app
   env: prod
 ports:
   - port: 80
     protocol: TCP
     targetPort: app-port
     nodePort: 32001
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
 name: my-deployment
 namespace: ms
spec: 
 replicas: 1 
 strategy: 
  type: Recreate 
 selector: 
  matchLabels: 
   app: my-app 
 template: 
   metadata: 
    labels: 
     app: my-app 
     env: prod 
   spec: 
    containers: 
    - name: my-deployment-container 
      image: naresh2603/multi:v1
      imagePullPolicy: Always
      ports:
        - name: app-port
          containerPort: 8080
